const mongoose = require('mongoose');

const ChildSchema = new mongoose.Schema({
  agencyId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  age: { type: Number, required: true },
  gender: { type: String, required: true },
  state: { type: String, required: true },
  healthStatus: { type: String, required: true },
  education: { type: String, required: true },
  interests: [{ type: String }],
  adoptionStatus: { 
    type: String, 
    enum: ['available', 'pending', 'adopted'], 
    default: 'available' 
  },
  aiSummary: { type: String }, // Generated by Gemini
  // Real names and exact locations are omitted for privacy
  isIdentityProtected: { type: Boolean, default: true }
}, { timestamps: true });

module.exports = mongoose.model('Child', ChildSchema);
